CREATE SCHEMA IF NOT EXISTS flyway;

GRANT USAGE, CREATE ON SCHEMA flyway TO admin_user;

GRANT USAGE, CREATE ON SCHEMA flyway TO flyway_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA flyway
  GRANT ALL ON TABLES TO flyway_user;
